export const genres = [
  { label: "Horror", value: "horror" },
  { label: "Romance", value: "romance" },
  { label: "Action and Adventure", value: "action-adventure" },
  { label: "Mystery", value: "mystery" },
  { label: "Fantasy", value: "fantasy" },
  { label: "Science Fiction", value: "sci-fi" },
  { label: "Historical Fiction", value: "historical-fiction" },
  { label: "Thriller", value: "thriller" },
  { label: "Non-Fiction", value: "non-fiction" },
  { label: "Biography", value: "biography" },
  { label: "Self-Help", value: "self-help" },
  { label: "Poetry", value: "poetry" },
  { label: "Young Adult", value: "young-adult" },
  { label: "Children's Literature", value: "children" },
  { label: "Graphic Novel", value: "graphic-novel" },
  { label: "Dystopian", value: "dystopian" },
];
