import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Molecules/Header/Header";
import WindowBox from "@/components/Organism/Window/WindowBox";
import InputBox from "@/components/Molecules/InputBox/InputBox";
import { useState } from "react";
import SelectBox from "@/components/Molecules/SelectBox/SelectBox";
import { genres } from "@/constants/common";
import Button from "@/components/Atoms/Button/Button";

export default function Home() {
  const [character, setCharacter] = useState("");
  const [genre, setGenre] = useState("");

  const handleGenerate = () => {
    console.log({ character, genre });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header title="AI StoryTeller" />
        <div className={styles.content}>
          <WindowBox>
            <InputBox
              label="Character name"
              value={character}
              setValue={setCharacter}
            />
            <SelectBox
              label="Select Genre"
              list={genres}
              setAction={setGenre}
            />
            <Button label="generate" onClick={() => handleGenerate()} />
          </WindowBox>
        </div>
      </main>
    </>
  );
}
